version: '3.8'

services:
  postgres:
    container_name: psql
    image: postgres:15.5-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vault:
    container_name: vault
    image: hashicorp/vault:1.14
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: ${VAULT_DEV_LISTEN_ADDRESS}
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      HOST: ${HOST}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./vault_init.sh:/vault_init.sh
    command: >
      sh -c "vault server -dev & sleep 5 && /vault_init.sh && tail -f /dev/null"
    cap_add:
      - IPC_LOCK

volumes:
  postgres_data:
  vault_data:
